
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcyhzmfdrhqmvrmjcssz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjeWh6bWZkcmhxbXZybWpjc3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MzYyMzIsImV4cCI6MjA1NzAxMjIzMn0.ExwuV7UZuF7I31Q52Hvt4t7Dmqf0qgO7Lga9EcrQUJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
